/**
 *  register_map.h : OPT3101 Register Map.
 *  Copyright (C) 2019  Appiko
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef OPT3101_REGISTER_MAP_H
#define OPT3101_REGISTER_MAP_H
//INITIALIZATION FOR REGISTER DIG_GPO_SEL0
#define DIG_GPO_SEL0			0X0B ///< ADDRESS=11
#define DIG_GPO_SEL0_MSB			3
#define DIG_GPO_SEL0_LSB			0

//INITIALIZATION FOR REGISTER DIG_GPO_SEL1
#define DIG_GPO_SEL1			0X0B ///< ADDRESS=11
#define DIG_GPO_SEL1_MSB			7
#define DIG_GPO_SEL1_LSB			4

//INITIALIZATION FOR REGISTER DIG_GPO_SEL2
#define DIG_GPO_SEL2			0X0B ///< ADDRESS=11
#define DIG_GPO_SEL2_MSB			13
#define DIG_GPO_SEL2_LSB			10

//INITIALIZATION FOR REGISTER DIS_OVL_GATING
#define DIS_OVL_GATING			0X11 ///< ADDRESS=17
#define DIS_OVL_GATING_MSB			15
#define DIS_OVL_GATING_LSB			15

//INITIALIZATION FOR REGISTER PHASE_OUT
#define PHASE_OUT			0X08 ///< ADDRESS=8
#define PHASE_OUT_MSB			15
#define PHASE_OUT_LSB			0

//INITIALIZATION FOR REGISTER PHASE_OVERFLOW
#define PHASE_OVERFLOW			0X08 ///< ADDRESS=8
#define PHASE_OVERFLOW_MSB			16
#define PHASE_OVERFLOW_LSB			16

//INITIALIZATION FOR REGISTER HDR_MODE
#define HDR_MODE			0X08 ///< ADDRESS=8
#define HDR_MODE_MSB			17
#define HDR_MODE_LSB			17

//INITIALIZATION FOR REGISTER TX_CHANNEL
#define TX_CHANNEL			0X08 ///< ADDRESS=8
#define TX_CHANNEL_MSB			19
#define TX_CHANNEL_LSB			18

//INITIALIZATION FOR REGISTER FRAME_STATUS
#define FRAME_STATUS			0X08 ///< ADDRESS=8
#define FRAME_STATUS_MSB			20
#define FRAME_STATUS_LSB			20

//INITIALIZATION FOR REGISTER MOD_FREQ
#define MOD_FREQ			0X08 ///< ADDRESS=8
#define MOD_FREQ_MSB			21
#define MOD_FREQ_LSB			21

//INITIALIZATION FOR REGISTER FRAME_COUNT0
#define FRAME_COUNT0			0X08 ///< ADDRESS=8
#define FRAME_COUNT0_MSB			23
#define FRAME_COUNT0_LSB			23

//INITIALIZATION FOR REGISTER AMP_OUT
#define AMP_OUT			0X09 ///< ADDRESS=9
#define AMP_OUT_MSB			15
#define AMP_OUT_LSB			0

//INITIALIZATION FOR REGISTER FRAME_COUNT1
#define FRAME_COUNT1			0X09 ///< ADDRESS=9
#define FRAME_COUNT1_MSB			17
#define FRAME_COUNT1_LSB			16

//INITIALIZATION FOR REGISTER SIG_OVL_FLAG
#define SIG_OVL_FLAG			0X09 ///< ADDRESS=9
#define SIG_OVL_FLAG_MSB			18
#define SIG_OVL_FLAG_LSB			18

//INITIALIZATION FOR REGISTER DEALIAS_BIN
#define DEALIAS_BIN			0X09 ///< ADDRESS=9
#define DEALIAS_BIN_MSB			23
#define DEALIAS_BIN_LSB			20

//INITIALIZATION FOR REGISTER FRAME_COUNT2
#define FRAME_COUNT2			0X0A ///< ADDRESS=10
#define FRAME_COUNT2_MSB			1
#define FRAME_COUNT2_LSB			0

//INITIALIZATION FOR REGISTER AMB_DATA
#define AMB_DATA			0X0A ///< ADDRESS=10
#define AMB_DATA_MSB			11
#define AMB_DATA_LSB			2

//INITIALIZATION FOR REGISTER TMAIN
#define TMAIN			0X0A ///< ADDRESS=10
#define TMAIN_MSB			23
#define TMAIN_LSB			12

//INITIALIZATION FOR REGISTER AMPLITUDE_MIN_THR
#define AMPLITUDE_MIN_THR_1			0X10 ///< ADDRESS=16
#define AMPLITUDE_MIN_THR_MSB_1			23
#define AMPLITUDE_MIN_THR_LSB_1			16
#define AMPLITUDE_MIN_THR			0X11 ///< ADDRESS=17
#define AMPLITUDE_MIN_THR_MSB			23
#define AMPLITUDE_MIN_THR_LSB			16

//INITIALIZATION FOR REGISTER AMB_OVL_FLAG
#define AMB_OVL_FLAG			0X08 ///< ADDRESS=8
#define AMB_OVL_FLAG_MSB			22
#define AMB_OVL_FLAG_LSB			22

//INITIALIZATION FOR REGISTER PHASE_OVERFLOW_F2
#define PHASE_OVERFLOW_F2			0X09 ///< ADDRESS=9
#define PHASE_OVERFLOW_F2_MSB			19
#define PHASE_OVERFLOW_F2_LSB			19

//INITIALIZATION FOR REGISTER REF_COUNT_LIMIT
#define REF_COUNT_LIMIT			0X0F ///< ADDRESS=15
#define REF_COUNT_LIMIT_MSB			14
#define REF_COUNT_LIMIT_LSB			0

//INITIALIZATION FOR REGISTER START_FREQ_CALIB
#define START_FREQ_CALIB			0X0F ///< ADDRESS=15
#define START_FREQ_CALIB_MSB			16
#define START_FREQ_CALIB_LSB			16

//INITIALIZATION FOR REGISTER SYS_CLK_DIVIDER
#define SYS_CLK_DIVIDER			0X0F ///< ADDRESS=15
#define SYS_CLK_DIVIDER_MSB			20
#define SYS_CLK_DIVIDER_LSB			17

//INITIALIZATION FOR REGISTER FREQ_COUNT_READ_REG
#define FREQ_COUNT_READ_REG			0X10 ///< ADDRESS=16
#define FREQ_COUNT_READ_REG_MSB			14
#define FREQ_COUNT_READ_REG_LSB			0

//INITIALIZATION FOR REGISTER FREQ_COUNT_REG
#define FREQ_COUNT_REG			0X11 ///< ADDRESS=17
#define FREQ_COUNT_REG_MSB			14
#define FREQ_COUNT_REG_LSB			0

//INITIALIZATION FOR REGISTER EN_AUTO_FREQ_COUNT
#define EN_AUTO_FREQ_COUNT			0X0F ///< ADDRESS=15
#define EN_AUTO_FREQ_COUNT_MSB			21
#define EN_AUTO_FREQ_COUNT_LSB			21

//INITIALIZATION FOR REGISTER EN_FLOOP
#define EN_FLOOP			0X0F ///< ADDRESS=15
#define EN_FLOOP_MSB			22
#define EN_FLOOP_LSB			22

//INITIALIZATION FOR REGISTER EN_FREQ_CORR
#define EN_FREQ_CORR			0X0F ///< ADDRESS=15
#define EN_FREQ_CORR_MSB			23
#define EN_FREQ_CORR_LSB			23

//INITIALIZATION FOR REGISTER EN_CONT_FCALIB
#define EN_CONT_FCALIB			0X10 ///< ADDRESS=16
#define EN_CONT_FCALIB_MSB			15
#define EN_CONT_FCALIB_LSB			15

//INITIALIZATION FOR REGISTER MONOSHOT_BIT
#define MONOSHOT_BIT			0X00 ///< ADDRESS=0
#define MONOSHOT_BIT_MSB			23
#define MONOSHOT_BIT_LSB			23

//INITIALIZATION FOR REGISTER MONOSHOT_MODE
#define MONOSHOT_MODE			0X27 ///< ADDRESS=39
#define MONOSHOT_MODE_MSB			1
#define MONOSHOT_MODE_LSB			0

//INITIALIZATION FOR REGISTER POWERUP_DELAY
#define POWERUP_DELAY			0X26 ///< ADDRESS=38
#define POWERUP_DELAY_MSB			23
#define POWERUP_DELAY_LSB			10

//INITIALIZATION FOR REGISTER MONOSHOT_NUMFRAME
#define MONOSHOT_NUMFRAME			0X27 ///< ADDRESS=39
#define MONOSHOT_NUMFRAME_MSB			7
#define MONOSHOT_NUMFRAME_LSB			2

//INITIALIZATION FOR REGISTER MONOSHOT_FZ_CLKCNT
#define MONOSHOT_FZ_CLKCNT			0X27 ///< ADDRESS=39
#define MONOSHOT_FZ_CLKCNT_MSB			23
#define MONOSHOT_FZ_CLKCNT_LSB			8

//INITIALIZATION FOR REGISTER EN_TX_SWITCH
#define EN_TX_SWITCH			0X2A ///< ADDRESS=42
#define EN_TX_SWITCH_MSB			0
#define EN_TX_SWITCH_LSB			0

//INITIALIZATION FOR REGISTER SEL_TX_CH
#define SEL_TX_CH			0X2A ///< ADDRESS=42
#define SEL_TX_CH_MSB			2
#define SEL_TX_CH_LSB			1

//INITIALIZATION FOR REGISTER TX_SEQ_REG
#define TX_SEQ_REG			0X2A ///< ADDRESS=42
#define TX_SEQ_REG_MSB			14
#define TX_SEQ_REG_LSB			3

//INITIALIZATION FOR REGISTER EN_ADAPTIVE_HDR
#define EN_ADAPTIVE_HDR			0X2A ///< ADDRESS=42
#define EN_ADAPTIVE_HDR_MSB			15
#define EN_ADAPTIVE_HDR_LSB			15

//INITIALIZATION FOR REGISTER SEL_HDR_MODE
#define SEL_HDR_MODE			0X2A ///< ADDRESS=42
#define SEL_HDR_MODE_MSB			16
#define SEL_HDR_MODE_LSB			16

//INITIALIZATION FOR REGISTER HDR_THR_LOW
#define HDR_THR_LOW			0X2C ///< ADDRESS=44
#define HDR_THR_LOW_MSB			15
#define HDR_THR_LOW_LSB			0

//INITIALIZATION FOR REGISTER HDR_THR_HIGH
#define HDR_THR_HIGH			0X2B ///< ADDRESS=43
#define HDR_THR_HIGH_MSB			15
#define HDR_THR_HIGH_LSB			0

//INITIALIZATION FOR REGISTER ILLUM_SCALE_L_TX0
#define ILLUM_SCALE_L_TX0			0X2B ///< ADDRESS=43
#define ILLUM_SCALE_L_TX0_MSB			18
#define ILLUM_SCALE_L_TX0_LSB			16

//INITIALIZATION FOR REGISTER ILLUM_DAC_L_TX0
#define ILLUM_DAC_L_TX0			0X29 ///< ADDRESS=41
#define ILLUM_DAC_L_TX0_MSB			4
#define ILLUM_DAC_L_TX0_LSB			0

//INITIALIZATION FOR REGISTER ILLUM_SCALE_H_TX0
#define ILLUM_SCALE_H_TX0			0X2B ///< ADDRESS=43
#define ILLUM_SCALE_H_TX0_MSB			21
#define ILLUM_SCALE_H_TX0_LSB			19

//INITIALIZATION FOR REGISTER ILLUM_DAC_H_TX0
#define ILLUM_DAC_H_TX0			0X29 ///< ADDRESS=41
#define ILLUM_DAC_H_TX0_MSB			9
#define ILLUM_DAC_H_TX0_LSB			5

//INITIALIZATION FOR REGISTER ILLUM_SCALE_L_TX1
#define ILLUM_SCALE_L_TX1			0X2C ///< ADDRESS=44
#define ILLUM_SCALE_L_TX1_MSB			18
#define ILLUM_SCALE_L_TX1_LSB			16

//INITIALIZATION FOR REGISTER ILLUM_DAC_L_TX1
#define ILLUM_DAC_L_TX1			0X29 ///< ADDRESS=41
#define ILLUM_DAC_L_TX1_MSB			14
#define ILLUM_DAC_L_TX1_LSB			10

//INITIALIZATION FOR REGISTER ILLUM_SCALE_H_TX1
#define ILLUM_SCALE_H_TX1			0X2C ///< ADDRESS=44
#define ILLUM_SCALE_H_TX1_MSB			21
#define ILLUM_SCALE_H_TX1_LSB			19

//INITIALIZATION FOR REGISTER ILLUM_DAC_H_TX1
#define ILLUM_DAC_H_TX1			0X29 ///< ADDRESS=41
#define ILLUM_DAC_H_TX1_MSB			19
#define ILLUM_DAC_H_TX1_LSB			15

//INITIALIZATION FOR REGISTER ILLUM_SCALE_L_TX2
#define ILLUM_SCALE_L_TX2			0XB9 ///< ADDRESS=185
#define ILLUM_SCALE_L_TX2_MSB			20
#define ILLUM_SCALE_L_TX2_LSB			18

//INITIALIZATION FOR REGISTER ILLUM_DAC_L_TX2
#define ILLUM_DAC_L_TX2_1			0X29 ///< ADDRESS=41
#define ILLUM_DAC_L_TX2_MSB_1			23
#define ILLUM_DAC_L_TX2_LSB_1			20
#define ILLUM_DAC_L_TX2			0X2A ///< ADDRESS=42
#define ILLUM_DAC_L_TX2_MSB			23
#define ILLUM_DAC_L_TX2_LSB			23

//INITIALIZATION FOR REGISTER ILLUM_SCALE_H_TX2
#define ILLUM_SCALE_H_TX2			0XB9 ///< ADDRESS=185
#define ILLUM_SCALE_H_TX2_MSB			23
#define ILLUM_SCALE_H_TX2_LSB			21

//INITIALIZATION FOR REGISTER ILLUM_DAC_H_TX2
#define ILLUM_DAC_H_TX2			0X2A ///< ADDRESS=42
#define ILLUM_DAC_H_TX2_MSB			22
#define ILLUM_DAC_H_TX2_LSB			18

//INITIALIZATION FOR REGISTER AMB_ADC_IN_TX0
#define AMB_ADC_IN_TX0			0XB9 ///< ADDRESS=185
#define AMB_ADC_IN_TX0_MSB			13
#define AMB_ADC_IN_TX0_LSB			12

//INITIALIZATION FOR REGISTER AMB_ADC_IN_TX1
#define AMB_ADC_IN_TX1			0XB9 ///< ADDRESS=185
#define AMB_ADC_IN_TX1_MSB			15
#define AMB_ADC_IN_TX1_LSB			14

//INITIALIZATION FOR REGISTER AMB_ADC_IN_TX2
#define AMB_ADC_IN_TX2			0XB9 ///< ADDRESS=185
#define AMB_ADC_IN_TX2_MSB			17
#define AMB_ADC_IN_TX2_LSB			16

//INITIALIZATION FOR REGISTER GIVE_DEALIAS_DATA
#define GIVE_DEALIAS_DATA			0XB8 ///< ADDRESS=184
#define GIVE_DEALIAS_DATA_MSB			20
#define GIVE_DEALIAS_DATA_LSB			20

//INITIALIZATION FOR REGISTER EN_DEALIAS_MEAS
#define EN_DEALIAS_MEAS			0X40 ///< ADDRESS=64
#define EN_DEALIAS_MEAS_MSB			0
#define EN_DEALIAS_MEAS_LSB			0

//INITIALIZATION FOR REGISTER NCR_CONFIG
#define NCR_CONFIG			0X40 ///< ADDRESS=64
#define NCR_CONFIG_MSB			21
#define NCR_CONFIG_LSB			21

//INITIALIZATION FOR REGISTER ALPHA0_DEALIAS_SCALE
#define ALPHA0_DEALIAS_SCALE			0X40 ///< ADDRESS=64
#define ALPHA0_DEALIAS_SCALE_MSB			14
#define ALPHA0_DEALIAS_SCALE_LSB			9

//INITIALIZATION FOR REGISTER BETA0_DEALIAS_SCALE
#define BETA0_DEALIAS_SCALE			0X40 ///< ADDRESS=64
#define BETA0_DEALIAS_SCALE_MSB			20
#define BETA0_DEALIAS_SCALE_LSB			15

//INITIALIZATION FOR REGISTER ALPHA1_DEALIAS_SCALE
#define ALPHA1_DEALIAS_SCALE			0X41 ///< ADDRESS=65
#define ALPHA1_DEALIAS_SCALE_MSB			5
#define ALPHA1_DEALIAS_SCALE_LSB			0

//INITIALIZATION FOR REGISTER BETA1_DEALIAS_SCALE
#define BETA1_DEALIAS_SCALE			0X41 ///< ADDRESS=65
#define BETA1_DEALIAS_SCALE_MSB			11
#define BETA1_DEALIAS_SCALE_LSB			6

//INITIALIZATION FOR REGISTER EN_MULTI_FREQ_PHASE
#define EN_MULTI_FREQ_PHASE			0X40 ///< ADDRESS=64
#define EN_MULTI_FREQ_PHASE_MSB			22
#define EN_MULTI_FREQ_PHASE_LSB			22

//INITIALIZATION FOR REGISTER TEMP_AVG_MAIN
#define TEMP_AVG_MAIN			0X03 ///< ADDRESS=3
#define TEMP_AVG_MAIN_MSB			23
#define TEMP_AVG_MAIN_LSB			22

//INITIALIZATION FOR REGISTER DIS_OVL_FOR_HDR_METH1
#define DIS_OVL_FOR_HDR_METH1			0XB8 ///< ADDRESS=184
#define DIS_OVL_FOR_HDR_METH1_MSB			21
#define DIS_OVL_FOR_HDR_METH1_LSB			21

//INITIALIZATION FOR REGISTER EN_OVL_FOR_HDR_METH2
#define EN_OVL_FOR_HDR_METH2			0XB8 ///< ADDRESS=184
#define EN_OVL_FOR_HDR_METH2_MSB			22
#define EN_OVL_FOR_HDR_METH2_LSB			22

//INITIALIZATION FOR REGISTER EN_TX1_ON_TX0
#define EN_TX1_ON_TX0			0XB9 ///< ADDRESS=185
#define EN_TX1_ON_TX0_MSB			10
#define EN_TX1_ON_TX0_LSB			10

//INITIALIZATION FOR REGISTER EN_TX2_ON_TX0
#define EN_TX2_ON_TX0			0XB9 ///< ADDRESS=185
#define EN_TX2_ON_TX0_MSB			11
#define EN_TX2_ON_TX0_LSB			11

//INITIALIZATION FOR REGISTER CLIP_MODE_FC
#define CLIP_MODE_FC			0X50 ///< ADDRESS=80
#define CLIP_MODE_FC_MSB			0
#define CLIP_MODE_FC_LSB			0

//INITIALIZATION FOR REGISTER CLIP_MODE_NL
#define CLIP_MODE_NL			0X50 ///< ADDRESS=80
#define CLIP_MODE_NL_MSB			1
#define CLIP_MODE_NL_LSB			1

//INITIALIZATION FOR REGISTER CLIP_MODE_TEMP
#define CLIP_MODE_TEMP			0X50 ///< ADDRESS=80
#define CLIP_MODE_TEMP_MSB			2
#define CLIP_MODE_TEMP_LSB			2

//INITIALIZATION FOR REGISTER CLIP_MODE_OFFSET
#define CLIP_MODE_OFFSET			0X50 ///< ADDRESS=80
#define CLIP_MODE_OFFSET_MSB			3
#define CLIP_MODE_OFFSET_LSB			3

//INITIALIZATION FOR REGISTER DISABLE_SYNCING
#define DISABLE_SYNCING			0X50 ///< ADDRESS=80
#define DISABLE_SYNCING_MSB			21
#define DISABLE_SYNCING_LSB			21

//INITIALIZATION FOR REGISTER FORCE_EN_SLAVE
#define FORCE_EN_SLAVE			0X00 ///< ADDRESS=0
#define FORCE_EN_SLAVE_MSB			22
#define FORCE_EN_SLAVE_LSB			22

//INITIALIZATION FOR REGISTER FORCE_EN_BYPASS
#define FORCE_EN_BYPASS			0X00 ///< ADDRESS=0
#define FORCE_EN_BYPASS_MSB			21
#define FORCE_EN_BYPASS_LSB			21

//INITIALIZATION FOR REGISTER OVERRIDE_CLKGEN_REG
#define OVERRIDE_CLKGEN_REG			0X50 ///< ADDRESS=80
#define OVERRIDE_CLKGEN_REG_MSB			22
#define OVERRIDE_CLKGEN_REG_LSB			22

//INITIALIZATION FOR REGISTER SOFTWARE_RESET
#define SOFTWARE_RESET			0X00 ///< ADDRESS=0
#define SOFTWARE_RESET_MSB			0
#define SOFTWARE_RESET_LSB			0

//INITIALIZATION FOR REGISTER DIS_TG_ACONF
#define DIS_TG_ACONF			0X80 ///< ADDRESS=128
#define DIS_TG_ACONF_MSB			23
#define DIS_TG_ACONF_LSB			23

//INITIALIZATION FOR REGISTER CAPTURE_CLK_CNT
#define CAPTURE_CLK_CNT			0XA0 ///< ADDRESS=160
#define CAPTURE_CLK_CNT_MSB			15
#define CAPTURE_CLK_CNT_LSB			0

//INITIALIZATION FOR REGISTER TG_EN
#define TG_EN			0X80 ///< ADDRESS=128
#define TG_EN_MSB			0
#define TG_EN_LSB			0

//INITIALIZATION FOR REGISTER NUM_SUB_FRAMES
#define NUM_SUB_FRAMES			0X9F ///< ADDRESS=159
#define NUM_SUB_FRAMES_MSB			11
#define NUM_SUB_FRAMES_LSB			0

//INITIALIZATION FOR REGISTER NUM_AVG_SUB_FRAMES
#define NUM_AVG_SUB_FRAMES			0X9F ///< ADDRESS=159
#define NUM_AVG_SUB_FRAMES_MSB			23
#define NUM_AVG_SUB_FRAMES_LSB			12

//INITIALIZATION FOR REGISTER SUB_VD_CLK_CNT
#define SUB_VD_CLK_CNT			0X80 ///< ADDRESS=128
#define SUB_VD_CLK_CNT_MSB			16
#define SUB_VD_CLK_CNT_LSB			1

//INITIALIZATION FOR REGISTER TG_ILLUMEN_START
#define TG_ILLUMEN_START			0X8F ///< ADDRESS=143
#define TG_ILLUMEN_START_MSB			15
#define TG_ILLUMEN_START_LSB			0

//INITIALIZATION FOR REGISTER TG_ILLUMEN_END
#define TG_ILLUMEN_END			0X90 ///< ADDRESS=144
#define TG_ILLUMEN_END_MSB			15
#define TG_ILLUMEN_END_LSB			0

//INITIALIZATION FOR REGISTER TG_ILLUMEN_MASK_START
#define TG_ILLUMEN_MASK_START			0X9C ///< ADDRESS=156
#define TG_ILLUMEN_MASK_START_MSB			11
#define TG_ILLUMEN_MASK_START_LSB			0

//INITIALIZATION FOR REGISTER TG_ILLUMEN_MASK_END
#define TG_ILLUMEN_MASK_END			0X9C ///< ADDRESS=156
#define TG_ILLUMEN_MASK_END_MSB			23
#define TG_ILLUMEN_MASK_END_LSB			12

//INITIALIZATION FOR REGISTER TG_AFE_RST_START
#define TG_AFE_RST_START			0X83 ///< ADDRESS=131
#define TG_AFE_RST_START_MSB			15
#define TG_AFE_RST_START_LSB			0

//INITIALIZATION FOR REGISTER TG_AFE_RST_END
#define TG_AFE_RST_END			0X84 ///< ADDRESS=132
#define TG_AFE_RST_END_MSB			15
#define TG_AFE_RST_END_LSB			0

//INITIALIZATION FOR REGISTER TG_SEQ_INT_START
#define TG_SEQ_INT_START			0X85 ///< ADDRESS=133
#define TG_SEQ_INT_START_MSB			15
#define TG_SEQ_INT_START_LSB			0

//INITIALIZATION FOR REGISTER TG_SEQ_INT_END
#define TG_SEQ_INT_END			0X86 ///< ADDRESS=134
#define TG_SEQ_INT_END_MSB			15
#define TG_SEQ_INT_END_LSB			0

//INITIALIZATION FOR REGISTER TG_CAPTURE_START
#define TG_CAPTURE_START			0X87 ///< ADDRESS=135
#define TG_CAPTURE_START_MSB			15
#define TG_CAPTURE_START_LSB			0

//INITIALIZATION FOR REGISTER TG_CAPTURE_END
#define TG_CAPTURE_END			0X88 ///< ADDRESS=136
#define TG_CAPTURE_END_MSB			15
#define TG_CAPTURE_END_LSB			0

//INITIALIZATION FOR REGISTER TG_OVL_WINDOW_START
#define TG_OVL_WINDOW_START			0X89 ///< ADDRESS=137
#define TG_OVL_WINDOW_START_MSB			15
#define TG_OVL_WINDOW_START_LSB			0

//INITIALIZATION FOR REGISTER TG_OVL_WINDOW_END
#define TG_OVL_WINDOW_END			0X8A ///< ADDRESS=138
#define TG_OVL_WINDOW_END_MSB			15
#define TG_OVL_WINDOW_END_LSB			0

//INITIALIZATION FOR REGISTER TG_CALC_START
#define TG_CALC_START			0X91 ///< ADDRESS=145
#define TG_CALC_START_MSB			15
#define TG_CALC_START_LSB			0

//INITIALIZATION FOR REGISTER TG_CALC_END
#define TG_CALC_END			0X92 ///< ADDRESS=146
#define TG_CALC_END_MSB			15
#define TG_CALC_END_LSB			0

//INITIALIZATION FOR REGISTER TG_DYNPDN_START
#define TG_DYNPDN_START			0X93 ///< ADDRESS=147
#define TG_DYNPDN_START_MSB			15
#define TG_DYNPDN_START_LSB			0

//INITIALIZATION FOR REGISTER TG_DYNPDN_END
#define TG_DYNPDN_END			0X94 ///< ADDRESS=148
#define TG_DYNPDN_END_MSB			15
#define TG_DYNPDN_END_LSB			0

//INITIALIZATION FOR REGISTER TG_SEQ_INT_MASK_START
#define TG_SEQ_INT_MASK_START			0X97 ///< ADDRESS=151
#define TG_SEQ_INT_MASK_START_MSB			11
#define TG_SEQ_INT_MASK_START_LSB			0

//INITIALIZATION FOR REGISTER TG_SEQ_INT_MASK_END
#define TG_SEQ_INT_MASK_END			0X97 ///< ADDRESS=151
#define TG_SEQ_INT_MASK_END_MSB			23
#define TG_SEQ_INT_MASK_END_LSB			12

//INITIALIZATION FOR REGISTER TG_CAPTURE_MASK_START
#define TG_CAPTURE_MASK_START			0X98 ///< ADDRESS=152
#define TG_CAPTURE_MASK_START_MSB			11
#define TG_CAPTURE_MASK_START_LSB			0

//INITIALIZATION FOR REGISTER TG_CAPTURE_MASK_END
#define TG_CAPTURE_MASK_END			0X98 ///< ADDRESS=152
#define TG_CAPTURE_MASK_END_MSB			23
#define TG_CAPTURE_MASK_END_LSB			12

//INITIALIZATION FOR REGISTER TG_OVL_WINDOW_MASK_START
#define TG_OVL_WINDOW_MASK_START			0X99 ///< ADDRESS=153
#define TG_OVL_WINDOW_MASK_START_MSB			11
#define TG_OVL_WINDOW_MASK_START_LSB			0

//INITIALIZATION FOR REGISTER TG_OVL_WINDOW_MASK_END
#define TG_OVL_WINDOW_MASK_END			0X99 ///< ADDRESS=153
#define TG_OVL_WINDOW_MASK_END_MSB			23
#define TG_OVL_WINDOW_MASK_END_LSB			12

//INITIALIZATION FOR REGISTER TG_CALC_MASK_START
#define TG_CALC_MASK_START			0X9D ///< ADDRESS=157
#define TG_CALC_MASK_START_MSB			11
#define TG_CALC_MASK_START_LSB			0

//INITIALIZATION FOR REGISTER TG_CALC_MASK_END
#define TG_CALC_MASK_END			0X9D ///< ADDRESS=157
#define TG_CALC_MASK_END_MSB			23
#define TG_CALC_MASK_END_LSB			12

//INITIALIZATION FOR REGISTER TG_DYNPDN_MASK_START
#define TG_DYNPDN_MASK_START			0X9E ///< ADDRESS=158
#define TG_DYNPDN_MASK_START_MSB			11
#define TG_DYNPDN_MASK_START_LSB			0

//INITIALIZATION FOR REGISTER TG_DYNPDN_MASK_END
#define TG_DYNPDN_MASK_END			0X9E ///< ADDRESS=158
#define TG_DYNPDN_MASK_END_MSB			23
#define TG_DYNPDN_MASK_END_LSB			12

//INITIALIZATION FOR REGISTER EN_SEQUENCER
#define EN_SEQUENCER			0X14 ///< ADDRESS=20
#define EN_SEQUENCER_MSB			16
#define EN_SEQUENCER_LSB			16

//INITIALIZATION FOR REGISTER EN_PROCESSOR_VALUES
#define EN_PROCESSOR_VALUES			0X14 ///< ADDRESS=20
#define EN_PROCESSOR_VALUES_MSB			17
#define EN_PROCESSOR_VALUES_LSB			17

//INITIALIZATION FOR REGISTER STATUS_IN_REG
#define STATUS_IN_REG			0X14 ///< ADDRESS=20
#define STATUS_IN_REG_MSB			18
#define STATUS_IN_REG_LSB			18

//INITIALIZATION FOR REGISTER MUX_SEL_COMPIN
#define MUX_SEL_COMPIN			0X13 ///< ADDRESS=19
#define MUX_SEL_COMPIN_MSB			2
#define MUX_SEL_COMPIN_LSB			0

//INITIALIZATION FOR REGISTER COMPARE_REG1
#define COMPARE_REG1			0X13 ///< ADDRESS=19
#define COMPARE_REG1_MSB			18
#define COMPARE_REG1_LSB			3

//INITIALIZATION FOR REGISTER COMPARE_REG2
#define COMPARE_REG2			0X14 ///< ADDRESS=20
#define COMPARE_REG2_MSB			15
#define COMPARE_REG2_LSB			0

//INITIALIZATION FOR REGISTER DIS_INTERRUPT
#define DIS_INTERRUPT			0X14 ///< ADDRESS=20
#define DIS_INTERRUPT_MSB			19
#define DIS_INTERRUPT_LSB			19

//INITIALIZATION FOR REGISTER COMMAND0
#define COMMAND0			0X15 ///< ADDRESS=21
#define COMMAND0_MSB			11
#define COMMAND0_LSB			0

//INITIALIZATION FOR REGISTER COMMAND1
#define COMMAND1			0X15 ///< ADDRESS=21
#define COMMAND1_MSB			23
#define COMMAND1_LSB			12

//INITIALIZATION FOR REGISTER COMMAND2
#define COMMAND2			0X16 ///< ADDRESS=22
#define COMMAND2_MSB			11
#define COMMAND2_LSB			0

//INITIALIZATION FOR REGISTER COMMAND3
#define COMMAND3			0X16 ///< ADDRESS=22
#define COMMAND3_MSB			23
#define COMMAND3_LSB			12

//INITIALIZATION FOR REGISTER COMMAND4
#define COMMAND4			0X17 ///< ADDRESS=23
#define COMMAND4_MSB			11
#define COMMAND4_LSB			0

//INITIALIZATION FOR REGISTER COMMAND5
#define COMMAND5			0X17 ///< ADDRESS=23
#define COMMAND5_MSB			23
#define COMMAND5_LSB			12

//INITIALIZATION FOR REGISTER COMMAND6
#define COMMAND6			0X18 ///< ADDRESS=24
#define COMMAND6_MSB			11
#define COMMAND6_LSB			0

//INITIALIZATION FOR REGISTER COMMAND7
#define COMMAND7			0X18 ///< ADDRESS=24
#define COMMAND7_MSB			23
#define COMMAND7_LSB			12

//INITIALIZATION FOR REGISTER COMMAND8
#define COMMAND8			0X19 ///< ADDRESS=25
#define COMMAND8_MSB			11
#define COMMAND8_LSB			0

//INITIALIZATION FOR REGISTER COMMAND9
#define COMMAND9			0X19 ///< ADDRESS=25
#define COMMAND9_MSB			23
#define COMMAND9_LSB			12

//INITIALIZATION FOR REGISTER COMMAND10
#define COMMAND10			0X1A ///< ADDRESS=26
#define COMMAND10_MSB			11
#define COMMAND10_LSB			0

//INITIALIZATION FOR REGISTER COMMAND11
#define COMMAND11			0X1A ///< ADDRESS=26
#define COMMAND11_MSB			23
#define COMMAND11_LSB			12

//INITIALIZATION FOR REGISTER COMMAND12
#define COMMAND12			0X1B ///< ADDRESS=27
#define COMMAND12_MSB			11
#define COMMAND12_LSB			0

//INITIALIZATION FOR REGISTER COMMAND13
#define COMMAND13			0X1B ///< ADDRESS=27
#define COMMAND13_MSB			23
#define COMMAND13_LSB			12

//INITIALIZATION FOR REGISTER COMMAND14
#define COMMAND14			0X1C ///< ADDRESS=28
#define COMMAND14_MSB			11
#define COMMAND14_LSB			0

//INITIALIZATION FOR REGISTER COMMAND15
#define COMMAND15			0X1C ///< ADDRESS=28
#define COMMAND15_MSB			23
#define COMMAND15_LSB			12

//INITIALIZATION FOR REGISTER COMMAND16
#define COMMAND16			0X1D ///< ADDRESS=29
#define COMMAND16_MSB			11
#define COMMAND16_LSB			0

//INITIALIZATION FOR REGISTER COMMAND17
#define COMMAND17			0X1D ///< ADDRESS=29
#define COMMAND17_MSB			23
#define COMMAND17_LSB			12

//INITIALIZATION FOR REGISTER COMMAND18
#define COMMAND18			0X1E ///< ADDRESS=30
#define COMMAND18_MSB			11
#define COMMAND18_LSB			0

//INITIALIZATION FOR REGISTER COMMAND19
#define COMMAND19			0X1E ///< ADDRESS=30
#define COMMAND19_MSB			23
#define COMMAND19_LSB			12

//INITIALIZATION FOR REGISTER FORCE_SCALE_VAL
#define FORCE_SCALE_VAL			0X2E ///< ADDRESS=46
#define FORCE_SCALE_VAL_MSB			2
#define FORCE_SCALE_VAL_LSB			0

//INITIALIZATION FOR REGISTER DIS_AUTO_SCALE
#define DIS_AUTO_SCALE			0X2E ///< ADDRESS=46
#define DIS_AUTO_SCALE_MSB			3
#define DIS_AUTO_SCALE_LSB			3

//INITIALIZATION FOR REGISTER DISABLE_CONF_RESCALE
#define DISABLE_CONF_RESCALE			0X2E ///< ADDRESS=46
#define DISABLE_CONF_RESCALE_MSB			13
#define DISABLE_CONF_RESCALE_LSB			13

//INITIALIZATION FOR REGISTER INT_XTALK_CALIB
#define INT_XTALK_CALIB			0X2E ///< ADDRESS=46
#define INT_XTALK_CALIB_MSB			4
#define INT_XTALK_CALIB_LSB			4

//INITIALIZATION FOR REGISTER XTALK_FILT_TIME_CONST
#define XTALK_FILT_TIME_CONST			0X2E ///< ADDRESS=46
#define XTALK_FILT_TIME_CONST_MSB			23
#define XTALK_FILT_TIME_CONST_LSB			20

//INITIALIZATION FOR REGISTER USE_XTALK_FILT_INT
#define USE_XTALK_FILT_INT			0X2E ///< ADDRESS=46
#define USE_XTALK_FILT_INT_MSB			5
#define USE_XTALK_FILT_INT_LSB			5

//INITIALIZATION FOR REGISTER USE_XTALK_REG_INT
#define USE_XTALK_REG_INT			0X2E ///< ADDRESS=46
#define USE_XTALK_REG_INT_MSB			6
#define USE_XTALK_REG_INT_LSB			6

//INITIALIZATION FOR REGISTER IQ_READ_DATA_SEL
#define IQ_READ_DATA_SEL			0X2E ///< ADDRESS=46
#define IQ_READ_DATA_SEL_MSB			11
#define IQ_READ_DATA_SEL_LSB			9

//INITIALIZATION FOR REGISTER IPHASE_XTALK
#define IPHASE_XTALK			0X3B ///< ADDRESS=59
#define IPHASE_XTALK_MSB			23
#define IPHASE_XTALK_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK
#define QPHASE_XTALK			0X3C ///< ADDRESS=60
#define QPHASE_XTALK_MSB			23
#define QPHASE_XTALK_LSB			0

//INITIALIZATION FOR REGISTER INT_XTALK_REG_SCALE
#define INT_XTALK_REG_SCALE			0X2E ///< ADDRESS=46
#define INT_XTALK_REG_SCALE_MSB			16
#define INT_XTALK_REG_SCALE_LSB			14

//INITIALIZATION FOR REGISTER IPHASE_XTALK_INT_REG
#define IPHASE_XTALK_INT_REG			0X3D ///< ADDRESS=61
#define IPHASE_XTALK_INT_REG_MSB			15
#define IPHASE_XTALK_INT_REG_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK_INT_REG
#define QPHASE_XTALK_INT_REG			0X3E ///< ADDRESS=62
#define QPHASE_XTALK_INT_REG_MSB			15
#define QPHASE_XTALK_INT_REG_LSB			0

//INITIALIZATION FOR REGISTER ILLUM_XTALK_CALIB
#define ILLUM_XTALK_CALIB			0X2E ///< ADDRESS=46
#define ILLUM_XTALK_CALIB_MSB			12
#define ILLUM_XTALK_CALIB_LSB			12

//INITIALIZATION FOR REGISTER ILLUM_XTALK_REG_SCALE
#define ILLUM_XTALK_REG_SCALE			0X2E ///< ADDRESS=46
#define ILLUM_XTALK_REG_SCALE_MSB			19
#define ILLUM_XTALK_REG_SCALE_LSB			17

//INITIALIZATION FOR REGISTER USE_XTALK_FILT_ILLUM
#define USE_XTALK_FILT_ILLUM			0X2E ///< ADDRESS=46
#define USE_XTALK_FILT_ILLUM_MSB			7
#define USE_XTALK_FILT_ILLUM_LSB			7

//INITIALIZATION FOR REGISTER USE_XTALK_REG_ILLUM
#define USE_XTALK_REG_ILLUM			0X2E ///< ADDRESS=46
#define USE_XTALK_REG_ILLUM_MSB			8
#define USE_XTALK_REG_ILLUM_LSB			8

//INITIALIZATION FOR REGISTER IPHASE_XTALK_REG_HDR0_TX0
#define IPHASE_XTALK_REG_HDR0_TX0			0X2F ///< ADDRESS=47
#define IPHASE_XTALK_REG_HDR0_TX0_MSB			15
#define IPHASE_XTALK_REG_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK_REG_HDR0_TX0
#define QPHASE_XTALK_REG_HDR0_TX0			0X30 ///< ADDRESS=48
#define QPHASE_XTALK_REG_HDR0_TX0_MSB			15
#define QPHASE_XTALK_REG_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER IPHASE_XTALK_REG_HDR1_TX0
#define IPHASE_XTALK_REG_HDR1_TX0			0X31 ///< ADDRESS=49
#define IPHASE_XTALK_REG_HDR1_TX0_MSB			15
#define IPHASE_XTALK_REG_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK_REG_HDR1_TX0
#define QPHASE_XTALK_REG_HDR1_TX0			0X32 ///< ADDRESS=50
#define QPHASE_XTALK_REG_HDR1_TX0_MSB			15
#define QPHASE_XTALK_REG_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER IPHASE_XTALK_REG_HDR0_TX1
#define IPHASE_XTALK_REG_HDR0_TX1			0X33 ///< ADDRESS=51
#define IPHASE_XTALK_REG_HDR0_TX1_MSB			15
#define IPHASE_XTALK_REG_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK_REG_HDR0_TX1
#define QPHASE_XTALK_REG_HDR0_TX1			0X34 ///< ADDRESS=52
#define QPHASE_XTALK_REG_HDR0_TX1_MSB			15
#define QPHASE_XTALK_REG_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER IPHASE_XTALK_REG_HDR1_TX1
#define IPHASE_XTALK_REG_HDR1_TX1			0X35 ///< ADDRESS=53
#define IPHASE_XTALK_REG_HDR1_TX1_MSB			15
#define IPHASE_XTALK_REG_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK_REG_HDR1_TX1
#define QPHASE_XTALK_REG_HDR1_TX1			0X36 ///< ADDRESS=54
#define QPHASE_XTALK_REG_HDR1_TX1_MSB			15
#define QPHASE_XTALK_REG_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER IPHASE_XTALK_REG_HDR0_TX2
#define IPHASE_XTALK_REG_HDR0_TX2			0X37 ///< ADDRESS=55
#define IPHASE_XTALK_REG_HDR0_TX2_MSB			15
#define IPHASE_XTALK_REG_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK_REG_HDR0_TX2
#define QPHASE_XTALK_REG_HDR0_TX2			0X38 ///< ADDRESS=56
#define QPHASE_XTALK_REG_HDR0_TX2_MSB			15
#define QPHASE_XTALK_REG_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER IPHASE_XTALK_REG_HDR1_TX2
#define IPHASE_XTALK_REG_HDR1_TX2			0X39 ///< ADDRESS=57
#define IPHASE_XTALK_REG_HDR1_TX2_MSB			15
#define IPHASE_XTALK_REG_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER QPHASE_XTALK_REG_HDR1_TX2
#define QPHASE_XTALK_REG_HDR1_TX2			0X3A ///< ADDRESS=58
#define QPHASE_XTALK_REG_HDR1_TX2_MSB			15
#define QPHASE_XTALK_REG_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER EN_TEMP_XTALK_CORR
#define EN_TEMP_XTALK_CORR			0X3A ///< ADDRESS=58
#define EN_TEMP_XTALK_CORR_MSB			16
#define EN_TEMP_XTALK_CORR_LSB			16

//INITIALIZATION FOR REGISTER SCALE_TEMP_COEFF_XTALK
#define SCALE_TEMP_COEFF_XTALK			0X3A ///< ADDRESS=58
#define SCALE_TEMP_COEFF_XTALK_MSB			19
#define SCALE_TEMP_COEFF_XTALK_LSB			17

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_IPHASE_HDR0_TX0
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX0			0X38 ///< ADDRESS=56
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX0_MSB			23
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX0_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_QPHASE_HDR0_TX0
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX0			0X39 ///< ADDRESS=57
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX0_MSB			23
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX0_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_IPHASE_HDR1_TX0
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX0			0X5E ///< ADDRESS=94
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX0_MSB			15
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX0_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_QPHASE_HDR1_TX0
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX0			0X60 ///< ADDRESS=96
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX0_MSB			7
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_IPHASE_HDR0_TX1
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX1			0X5E ///< ADDRESS=94
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX1_MSB			23
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX1_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_QPHASE_HDR0_TX1
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX1			0X60 ///< ADDRESS=96
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX1_MSB			15
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX1_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_IPHASE_HDR1_TX1
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX1			0X5F ///< ADDRESS=95
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX1_MSB			7
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_QPHASE_HDR1_TX1
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX1			0X60 ///< ADDRESS=96
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX1_MSB			23
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX1_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_IPHASE_HDR0_TX2
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX2			0X5F ///< ADDRESS=95
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX2_MSB			15
#define TEMP_COEFF_XTALK_IPHASE_HDR0_TX2_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_QPHASE_HDR0_TX2
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX2			0X61 ///< ADDRESS=97
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX2_MSB			7
#define TEMP_COEFF_XTALK_QPHASE_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_IPHASE_HDR1_TX2
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX2			0X5F ///< ADDRESS=95
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX2_MSB			23
#define TEMP_COEFF_XTALK_IPHASE_HDR1_TX2_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_XTALK_QPHASE_HDR1_TX2
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX2			0X61 ///< ADDRESS=97
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX2_MSB			15
#define TEMP_COEFF_XTALK_QPHASE_HDR1_TX2_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX0
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX0			0X36 ///< ADDRESS=54
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX0_MSB			23
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX0_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX0
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX0			0X37 ///< ADDRESS=55
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX0_MSB			23
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX0_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX0
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX0			0X5B ///< ADDRESS=91
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX0_MSB			7
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX1
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX1			0X5B ///< ADDRESS=91
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX1_MSB			15
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX1_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX1
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX1			0X5B ///< ADDRESS=91
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX1_MSB			23
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX1_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX2
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX2			0X5C ///< ADDRESS=92
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX2_MSB			7
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX2
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX2			0X5C ///< ADDRESS=92
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX2_MSB			15
#define TEMP_COEFF_ILLUM_XTALK_IPHASE_HDR1_TX2_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX0
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX0			0X5C ///< ADDRESS=92
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX0_MSB			23
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX0_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX1
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX1			0X5D ///< ADDRESS=93
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX1_MSB			7
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX1
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX1			0X5D ///< ADDRESS=93
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX1_MSB			15
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX1_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX2
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX2			0X5D ///< ADDRESS=93
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX2_MSB			23
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR0_TX2_LSB			16

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX2
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX2			0X5E ///< ADDRESS=94
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX2_MSB			7
#define TEMP_COEFF_ILLUM_XTALK_QPHASE_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER AMB_XTALK_QPHASE_COEFF
#define AMB_XTALK_QPHASE_COEFF			0X0C ///< ADDRESS=12
#define AMB_XTALK_QPHASE_COEFF_MSB			15
#define AMB_XTALK_QPHASE_COEFF_LSB			8

//INITIALIZATION FOR REGISTER AMB_XTALK_IPHASE_COEFF
#define AMB_XTALK_IPHASE_COEFF			0X0C ///< ADDRESS=12
#define AMB_XTALK_IPHASE_COEFF_MSB			7
#define AMB_XTALK_IPHASE_COEFF_LSB			0

//INITIALIZATION FOR REGISTER SCALE_AMB_COEFF_XTALK
#define SCALE_AMB_COEFF_XTALK			0X3A ///< ADDRESS=58
#define SCALE_AMB_COEFF_XTALK_MSB			22
#define SCALE_AMB_COEFF_XTALK_LSB			20

//INITIALIZATION FOR REGISTER EN_PHASE_CORR
#define EN_PHASE_CORR			0X43 ///< ADDRESS=67
#define EN_PHASE_CORR_MSB			0
#define EN_PHASE_CORR_LSB			0

//INITIALIZATION FOR REGISTER PHASE_OFFSET_HDR0_TX0
#define PHASE_OFFSET_HDR0_TX0			0X42 ///< ADDRESS=66
#define PHASE_OFFSET_HDR0_TX0_MSB			15
#define PHASE_OFFSET_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER PHASE_OFFSET_HDR1_TX0
#define PHASE_OFFSET_HDR1_TX0			0X51 ///< ADDRESS=81
#define PHASE_OFFSET_HDR1_TX0_MSB			15
#define PHASE_OFFSET_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER PHASE_OFFSET_HDR0_TX1
#define PHASE_OFFSET_HDR0_TX1			0X52 ///< ADDRESS=82
#define PHASE_OFFSET_HDR0_TX1_MSB			15
#define PHASE_OFFSET_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER PHASE_OFFSET_HDR1_TX1
#define PHASE_OFFSET_HDR1_TX1			0X53 ///< ADDRESS=83
#define PHASE_OFFSET_HDR1_TX1_MSB			15
#define PHASE_OFFSET_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER PHASE_OFFSET_HDR0_TX2
#define PHASE_OFFSET_HDR0_TX2			0X54 ///< ADDRESS=84
#define PHASE_OFFSET_HDR0_TX2_MSB			15
#define PHASE_OFFSET_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER PHASE_OFFSET_HDR1_TX2
#define PHASE_OFFSET_HDR1_TX2			0X55 ///< ADDRESS=85
#define PHASE_OFFSET_HDR1_TX2_MSB			15
#define PHASE_OFFSET_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER REVERSE_PHASE_BEFORE_OFFSET
#define REVERSE_PHASE_BEFORE_OFFSET			0X43 ///< ADDRESS=67
#define REVERSE_PHASE_BEFORE_OFFSET_MSB			9
#define REVERSE_PHASE_BEFORE_OFFSET_LSB			9

//INITIALIZATION FOR REGISTER PHASE2_OFFSET_HDR0_TX0
#define PHASE2_OFFSET_HDR0_TX0			0X44 ///< ADDRESS=68
#define PHASE2_OFFSET_HDR0_TX0_MSB			15
#define PHASE2_OFFSET_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER PHASE2_OFFSET_HDR1_TX0
#define PHASE2_OFFSET_HDR1_TX0			0X56 ///< ADDRESS=86
#define PHASE2_OFFSET_HDR1_TX0_MSB			15
#define PHASE2_OFFSET_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER PHASE2_OFFSET_HDR0_TX1
#define PHASE2_OFFSET_HDR0_TX1			0X57 ///< ADDRESS=87
#define PHASE2_OFFSET_HDR0_TX1_MSB			15
#define PHASE2_OFFSET_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER PHASE2_OFFSET_HDR1_TX1
#define PHASE2_OFFSET_HDR1_TX1			0X58 ///< ADDRESS=88
#define PHASE2_OFFSET_HDR1_TX1_MSB			15
#define PHASE2_OFFSET_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER PHASE2_OFFSET_HDR0_TX2
#define PHASE2_OFFSET_HDR0_TX2			0X59 ///< ADDRESS=89
#define PHASE2_OFFSET_HDR0_TX2_MSB			15
#define PHASE2_OFFSET_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER PHASE2_OFFSET_HDR1_TX2
#define PHASE2_OFFSET_HDR1_TX2			0X5A ///< ADDRESS=90
#define PHASE2_OFFSET_HDR1_TX2_MSB			15
#define PHASE2_OFFSET_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER EN_TEMP_CORR
#define EN_TEMP_CORR			0X43 ///< ADDRESS=67
#define EN_TEMP_CORR_MSB			1
#define EN_TEMP_CORR_LSB			1

//INITIALIZATION FOR REGISTER SCALE_PHASE_TEMP_COEFF
#define SCALE_PHASE_TEMP_COEFF			0X43 ///< ADDRESS=67
#define SCALE_PHASE_TEMP_COEFF_MSB			8
#define SCALE_PHASE_TEMP_COEFF_LSB			6

//INITIALIZATION FOR REGISTER TMAIN_CALIB_HDR0_TX0
#define TMAIN_CALIB_HDR0_TX0			0X47 ///< ADDRESS=71
#define TMAIN_CALIB_HDR0_TX0_MSB			11
#define TMAIN_CALIB_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_HDR0_TX0
#define TEMP_COEFF_MAIN_HDR0_TX0			0X45 ///< ADDRESS=69
#define TEMP_COEFF_MAIN_HDR0_TX0_MSB			11
#define TEMP_COEFF_MAIN_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER TMAIN_CALIB_HDR1_TX0
#define TMAIN_CALIB_HDR1_TX0			0X48 ///< ADDRESS=72
#define TMAIN_CALIB_HDR1_TX0_MSB			11
#define TMAIN_CALIB_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_HDR1_TX0
#define TEMP_COEFF_MAIN_HDR1_TX0			0X2D ///< ADDRESS=45
#define TEMP_COEFF_MAIN_HDR1_TX0_MSB			11
#define TEMP_COEFF_MAIN_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER TMAIN_CALIB_HDR0_TX1
#define TMAIN_CALIB_HDR0_TX1			0X49 ///< ADDRESS=73
#define TMAIN_CALIB_HDR0_TX1_MSB			11
#define TMAIN_CALIB_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_HDR0_TX1
#define TEMP_COEFF_MAIN_HDR0_TX1			0X2D ///< ADDRESS=45
#define TEMP_COEFF_MAIN_HDR0_TX1_MSB			23
#define TEMP_COEFF_MAIN_HDR0_TX1_LSB			12

//INITIALIZATION FOR REGISTER TMAIN_CALIB_HDR1_TX1
#define TMAIN_CALIB_HDR1_TX1			0X41 ///< ADDRESS=65
#define TMAIN_CALIB_HDR1_TX1_MSB			23
#define TMAIN_CALIB_HDR1_TX1_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_HDR1_TX1
#define TEMP_COEFF_MAIN_HDR1_TX1_1			0X2F ///< ADDRESS=47
#define TEMP_COEFF_MAIN_HDR1_TX1_MSB_1			23
#define TEMP_COEFF_MAIN_HDR1_TX1_LSB_1			16
#define TEMP_COEFF_MAIN_HDR1_TX1			0X30 ///< ADDRESS=48
#define TEMP_COEFF_MAIN_HDR1_TX1_MSB			23
#define TEMP_COEFF_MAIN_HDR1_TX1_LSB			20

//INITIALIZATION FOR REGISTER TMAIN_CALIB_HDR0_TX2
#define TMAIN_CALIB_HDR0_TX2			0X3F ///< ADDRESS=63
#define TMAIN_CALIB_HDR0_TX2_MSB			11
#define TMAIN_CALIB_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_HDR0_TX2
#define TEMP_COEFF_MAIN_HDR0_TX2_1			0X31 ///< ADDRESS=49
#define TEMP_COEFF_MAIN_HDR0_TX2_MSB_1			23
#define TEMP_COEFF_MAIN_HDR0_TX2_LSB_1			16
#define TEMP_COEFF_MAIN_HDR0_TX2			0X32 ///< ADDRESS=50
#define TEMP_COEFF_MAIN_HDR0_TX2_MSB			23
#define TEMP_COEFF_MAIN_HDR0_TX2_LSB			20

//INITIALIZATION FOR REGISTER TMAIN_CALIB_HDR1_TX2
#define TMAIN_CALIB_HDR1_TX2			0X45 ///< ADDRESS=69
#define TMAIN_CALIB_HDR1_TX2_MSB			23
#define TMAIN_CALIB_HDR1_TX2_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_HDR1_TX2
#define TEMP_COEFF_MAIN_HDR1_TX2_1			0X33 ///< ADDRESS=51
#define TEMP_COEFF_MAIN_HDR1_TX2_MSB_1			23
#define TEMP_COEFF_MAIN_HDR1_TX2_LSB_1			16
#define TEMP_COEFF_MAIN_HDR1_TX2			0X34 ///< ADDRESS=52
#define TEMP_COEFF_MAIN_HDR1_TX2_MSB			23
#define TEMP_COEFF_MAIN_HDR1_TX2_LSB			20

//INITIALIZATION FOR REGISTER TILLUM_CALIB_HDR0_TX0
#define TILLUM_CALIB_HDR0_TX0			0X47 ///< ADDRESS=71
#define TILLUM_CALIB_HDR0_TX0_MSB			23
#define TILLUM_CALIB_HDR0_TX0_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_HDR0_TX0
#define TEMP_COEFF_ILLUM_HDR0_TX0			0X46 ///< ADDRESS=70
#define TEMP_COEFF_ILLUM_HDR0_TX0_MSB			11
#define TEMP_COEFF_ILLUM_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER TILLUM_CALIB_HDR1_TX0
#define TILLUM_CALIB_HDR1_TX0			0X48 ///< ADDRESS=72
#define TILLUM_CALIB_HDR1_TX0_MSB			23
#define TILLUM_CALIB_HDR1_TX0_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_HDR1_TX0
#define TEMP_COEFF_ILLUM_HDR1_TX0_1			0X51 ///< ADDRESS=81
#define TEMP_COEFF_ILLUM_HDR1_TX0_MSB_1			23
#define TEMP_COEFF_ILLUM_HDR1_TX0_LSB_1			16
#define TEMP_COEFF_ILLUM_HDR1_TX0			0X52 ///< ADDRESS=82
#define TEMP_COEFF_ILLUM_HDR1_TX0_MSB			23
#define TEMP_COEFF_ILLUM_HDR1_TX0_LSB			20

//INITIALIZATION FOR REGISTER TILLUM_CALIB_HDR0_TX1
#define TILLUM_CALIB_HDR0_TX1			0X49 ///< ADDRESS=73
#define TILLUM_CALIB_HDR0_TX1_MSB			23
#define TILLUM_CALIB_HDR0_TX1_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_HDR0_TX1
#define TEMP_COEFF_ILLUM_HDR0_TX1_1			0X53 ///< ADDRESS=83
#define TEMP_COEFF_ILLUM_HDR0_TX1_MSB_1			23
#define TEMP_COEFF_ILLUM_HDR0_TX1_LSB_1			16
#define TEMP_COEFF_ILLUM_HDR0_TX1			0X54 ///< ADDRESS=84
#define TEMP_COEFF_ILLUM_HDR0_TX1_MSB			23
#define TEMP_COEFF_ILLUM_HDR0_TX1_LSB			20

//INITIALIZATION FOR REGISTER TILLUM_CALIB_HDR1_TX1
#define TILLUM_CALIB_HDR1_TX1			0X43 ///< ADDRESS=67
#define TILLUM_CALIB_HDR1_TX1_MSB			23
#define TILLUM_CALIB_HDR1_TX1_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_HDR1_TX1
#define TEMP_COEFF_ILLUM_HDR1_TX1_1			0X55 ///< ADDRESS=85
#define TEMP_COEFF_ILLUM_HDR1_TX1_MSB_1			23
#define TEMP_COEFF_ILLUM_HDR1_TX1_LSB_1			16
#define TEMP_COEFF_ILLUM_HDR1_TX1			0X56 ///< ADDRESS=86
#define TEMP_COEFF_ILLUM_HDR1_TX1_MSB			23
#define TEMP_COEFF_ILLUM_HDR1_TX1_LSB			20

//INITIALIZATION FOR REGISTER TILLUM_CALIB_HDR0_TX2
#define TILLUM_CALIB_HDR0_TX2			0X3F ///< ADDRESS=63
#define TILLUM_CALIB_HDR0_TX2_MSB			23
#define TILLUM_CALIB_HDR0_TX2_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_HDR0_TX2
#define TEMP_COEFF_ILLUM_HDR0_TX2_1			0X57 ///< ADDRESS=87
#define TEMP_COEFF_ILLUM_HDR0_TX2_MSB_1			23
#define TEMP_COEFF_ILLUM_HDR0_TX2_LSB_1			16
#define TEMP_COEFF_ILLUM_HDR0_TX2			0X58 ///< ADDRESS=88
#define TEMP_COEFF_ILLUM_HDR0_TX2_MSB			23
#define TEMP_COEFF_ILLUM_HDR0_TX2_LSB			20

//INITIALIZATION FOR REGISTER TILLUM_CALIB_HDR1_TX2
#define TILLUM_CALIB_HDR1_TX2			0X46 ///< ADDRESS=70
#define TILLUM_CALIB_HDR1_TX2_MSB			23
#define TILLUM_CALIB_HDR1_TX2_LSB			12

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_HDR1_TX2
#define TEMP_COEFF_ILLUM_HDR1_TX2_1			0X59 ///< ADDRESS=89
#define TEMP_COEFF_ILLUM_HDR1_TX2_MSB_1			23
#define TEMP_COEFF_ILLUM_HDR1_TX2_LSB_1			16
#define TEMP_COEFF_ILLUM_HDR1_TX2			0X5A ///< ADDRESS=90
#define TEMP_COEFF_ILLUM_HDR1_TX2_MSB			23
#define TEMP_COEFF_ILLUM_HDR1_TX2_LSB			20

//INITIALIZATION FOR REGISTER AMB_SAT_THR
#define AMB_SAT_THR			0X0D ///< ADDRESS=13
#define AMB_SAT_THR_MSB			16
#define AMB_SAT_THR_LSB			7

//INITIALIZATION FOR REGISTER AMB_CALIB
#define AMB_CALIB			0X0B ///< ADDRESS=11
#define AMB_CALIB_MSB			23
#define AMB_CALIB_LSB			14

//INITIALIZATION FOR REGISTER AMB_PHASE_CORR_PWL_COEFF0
#define AMB_PHASE_CORR_PWL_COEFF0			0X0C ///< ADDRESS=12
#define AMB_PHASE_CORR_PWL_COEFF0_MSB			23
#define AMB_PHASE_CORR_PWL_COEFF0_LSB			16

//INITIALIZATION FOR REGISTER AMB_PHASE_CORR_PWL_X0
#define AMB_PHASE_CORR_PWL_X0			0XB8 ///< ADDRESS=184
#define AMB_PHASE_CORR_PWL_X0_MSB			9
#define AMB_PHASE_CORR_PWL_X0_LSB			0

//INITIALIZATION FOR REGISTER AMB_PHASE_CORR_PWL_X1
#define AMB_PHASE_CORR_PWL_X1			0XB8 ///< ADDRESS=184
#define AMB_PHASE_CORR_PWL_X1_MSB			19
#define AMB_PHASE_CORR_PWL_X1_LSB			10

//INITIALIZATION FOR REGISTER AMB_PHASE_CORR_PWL_X2
#define AMB_PHASE_CORR_PWL_X2			0XB9 ///< ADDRESS=185
#define AMB_PHASE_CORR_PWL_X2_MSB			9
#define AMB_PHASE_CORR_PWL_X2_LSB			0

//INITIALIZATION FOR REGISTER AMB_PHASE_CORR_PWL_COEFF1
#define AMB_PHASE_CORR_PWL_COEFF1			0XB4 ///< ADDRESS=180
#define AMB_PHASE_CORR_PWL_COEFF1_MSB			7
#define AMB_PHASE_CORR_PWL_COEFF1_LSB			0

//INITIALIZATION FOR REGISTER AMB_PHASE_CORR_PWL_COEFF2
#define AMB_PHASE_CORR_PWL_COEFF2			0XB4 ///< ADDRESS=180
#define AMB_PHASE_CORR_PWL_COEFF2_MSB			15
#define AMB_PHASE_CORR_PWL_COEFF2_LSB			8

//INITIALIZATION FOR REGISTER AMB_PHASE_CORR_PWL_COEFF3
#define AMB_PHASE_CORR_PWL_COEFF3			0XB4 ///< ADDRESS=180
#define AMB_PHASE_CORR_PWL_COEFF3_MSB			23
#define AMB_PHASE_CORR_PWL_COEFF3_LSB			16

//INITIALIZATION FOR REGISTER SCALE_AMB_PHASE_CORR_COEFF
#define SCALE_AMB_PHASE_CORR_COEFF			0XB5 ///< ADDRESS=181
#define SCALE_AMB_PHASE_CORR_COEFF_MSB			2
#define SCALE_AMB_PHASE_CORR_COEFF_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_SQUARE_HDR0
#define TEMP_COEFF_ILLUM_SQUARE_HDR0			0XB6 ///< ADDRESS=182
#define TEMP_COEFF_ILLUM_SQUARE_HDR0_MSB			7
#define TEMP_COEFF_ILLUM_SQUARE_HDR0_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_ILLUM_SQUARE_HDR1
#define TEMP_COEFF_ILLUM_SQUARE_HDR1			0XB6 ///< ADDRESS=182
#define TEMP_COEFF_ILLUM_SQUARE_HDR1_MSB			15
#define TEMP_COEFF_ILLUM_SQUARE_HDR1_LSB			8

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_SQUARE_HDR0
#define TEMP_COEFF_MAIN_SQUARE_HDR0			0XB7 ///< ADDRESS=183
#define TEMP_COEFF_MAIN_SQUARE_HDR0_MSB			7
#define TEMP_COEFF_MAIN_SQUARE_HDR0_LSB			0

//INITIALIZATION FOR REGISTER TEMP_COEFF_MAIN_SQUARE_HDR1
#define TEMP_COEFF_MAIN_SQUARE_HDR1			0XB7 ///< ADDRESS=183
#define TEMP_COEFF_MAIN_SQUARE_HDR1_MSB			15
#define TEMP_COEFF_MAIN_SQUARE_HDR1_LSB			8

//INITIALIZATION FOR REGISTER SCALE_PHASE_TEMP_CORR_SQUARE
#define SCALE_PHASE_TEMP_CORR_SQUARE			0XB5 ///< ADDRESS=181
#define SCALE_PHASE_TEMP_CORR_SQUARE_MSB			5
#define SCALE_PHASE_TEMP_CORR_SQUARE_LSB			3

//INITIALIZATION FOR REGISTER EN_NL_CORR
#define EN_NL_CORR			0X4A ///< ADDRESS=74
#define EN_NL_CORR_MSB			0
#define EN_NL_CORR_LSB			0

//INITIALIZATION FOR REGISTER A1_COEFF_HDR0_TX0
#define A1_COEFF_HDR0_TX0			0X4B ///< ADDRESS=75
#define A1_COEFF_HDR0_TX0_MSB			15
#define A1_COEFF_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER A2_COEFF_HDR0_TX0
#define A2_COEFF_HDR0_TX0			0X4C ///< ADDRESS=76
#define A2_COEFF_HDR0_TX0_MSB			15
#define A2_COEFF_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER A3_COEFF_HDR0_TX0
#define A3_COEFF_HDR0_TX0			0X4D ///< ADDRESS=77
#define A3_COEFF_HDR0_TX0_MSB			15
#define A3_COEFF_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER A4_COEFF_HDR0_TX0
#define A4_COEFF_HDR0_TX0			0X4E ///< ADDRESS=78
#define A4_COEFF_HDR0_TX0_MSB			15
#define A4_COEFF_HDR0_TX0_LSB			0

//INITIALIZATION FOR REGISTER SCALE_NL_CORR_COEFF
#define SCALE_NL_CORR_COEFF			0X4A ///< ADDRESS=74
#define SCALE_NL_CORR_COEFF_MSB			19
#define SCALE_NL_CORR_COEFF_LSB			18

//INITIALIZATION FOR REGISTER A0_COEFF_HDR0_TX0
#define A0_COEFF_HDR0_TX0			0X4A ///< ADDRESS=74
#define A0_COEFF_HDR0_TX0_MSB			17
#define A0_COEFF_HDR0_TX0_LSB			2

//INITIALIZATION FOR REGISTER A0_COEFF_HDR1_TX0
#define A0_COEFF_HDR1_TX0			0XA2 ///< ADDRESS=162
#define A0_COEFF_HDR1_TX0_MSB			15
#define A0_COEFF_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER A0_COEFF_HDR0_TX1
#define A0_COEFF_HDR0_TX1			0XA3 ///< ADDRESS=163
#define A0_COEFF_HDR0_TX1_MSB			15
#define A0_COEFF_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER A0_COEFF_HDR1_TX1
#define A0_COEFF_HDR1_TX1			0XA4 ///< ADDRESS=164
#define A0_COEFF_HDR1_TX1_MSB			15
#define A0_COEFF_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER A0_COEFF_HDR0_TX2
#define A0_COEFF_HDR0_TX2			0XA5 ///< ADDRESS=165
#define A0_COEFF_HDR0_TX2_MSB			15
#define A0_COEFF_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER A0_COEFF_HDR1_TX2
#define A0_COEFF_HDR1_TX2			0XA6 ///< ADDRESS=166
#define A0_COEFF_HDR1_TX2_MSB			15
#define A0_COEFF_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER A1_COEFF_HDR1_TX0
#define A1_COEFF_HDR1_TX0			0XA7 ///< ADDRESS=167
#define A1_COEFF_HDR1_TX0_MSB			15
#define A1_COEFF_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER A1_COEFF_HDR0_TX1
#define A1_COEFF_HDR0_TX1			0XA8 ///< ADDRESS=168
#define A1_COEFF_HDR0_TX1_MSB			15
#define A1_COEFF_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER A1_COEFF_HDR1_TX1
#define A1_COEFF_HDR1_TX1			0XA9 ///< ADDRESS=169
#define A1_COEFF_HDR1_TX1_MSB			15
#define A1_COEFF_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER A1_COEFF_HDR0_TX2
#define A1_COEFF_HDR0_TX2			0XAA ///< ADDRESS=170
#define A1_COEFF_HDR0_TX2_MSB			15
#define A1_COEFF_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER A1_COEFF_HDR1_TX2
#define A1_COEFF_HDR1_TX2			0XAB ///< ADDRESS=171
#define A1_COEFF_HDR1_TX2_MSB			15
#define A1_COEFF_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER A2_COEFF_HDR1_TX0
#define A2_COEFF_HDR1_TX0			0XAC ///< ADDRESS=172
#define A2_COEFF_HDR1_TX0_MSB			15
#define A2_COEFF_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER A2_COEFF_HDR0_TX1
#define A2_COEFF_HDR0_TX1			0XAD ///< ADDRESS=173
#define A2_COEFF_HDR0_TX1_MSB			15
#define A2_COEFF_HDR0_TX1_LSB			0

//INITIALIZATION FOR REGISTER A2_COEFF_HDR1_TX1
#define A2_COEFF_HDR1_TX1			0XAE ///< ADDRESS=174
#define A2_COEFF_HDR1_TX1_MSB			15
#define A2_COEFF_HDR1_TX1_LSB			0

//INITIALIZATION FOR REGISTER A2_COEFF_HDR0_TX2
#define A2_COEFF_HDR0_TX2			0XAF ///< ADDRESS=175
#define A2_COEFF_HDR0_TX2_MSB			15
#define A2_COEFF_HDR0_TX2_LSB			0

//INITIALIZATION FOR REGISTER A2_COEFF_HDR1_TX2
#define A2_COEFF_HDR1_TX2			0XB0 ///< ADDRESS=176
#define A2_COEFF_HDR1_TX2_MSB			15
#define A2_COEFF_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER A3_COEFF_HDR1_TX0
#define A3_COEFF_HDR1_TX0			0XB1 ///< ADDRESS=177
#define A3_COEFF_HDR1_TX0_MSB			15
#define A3_COEFF_HDR1_TX0_LSB			0

//INITIALIZATION FOR REGISTER A3_COEFF_HDR0_TX1
#define A3_COEFF_HDR0_TX1_1			0XA2 ///< ADDRESS=162
#define A3_COEFF_HDR0_TX1_MSB_1			23
#define A3_COEFF_HDR0_TX1_LSB_1			16
#define A3_COEFF_HDR0_TX1			0XA3 ///< ADDRESS=163
#define A3_COEFF_HDR0_TX1_MSB			23
#define A3_COEFF_HDR0_TX1_LSB			16

//INITIALIZATION FOR REGISTER A3_COEFF_HDR1_TX1
#define A3_COEFF_HDR1_TX1_1			0XA4 ///< ADDRESS=164
#define A3_COEFF_HDR1_TX1_MSB_1			23
#define A3_COEFF_HDR1_TX1_LSB_1			16
#define A3_COEFF_HDR1_TX1			0XA5 ///< ADDRESS=165
#define A3_COEFF_HDR1_TX1_MSB			23
#define A3_COEFF_HDR1_TX1_LSB			16

//INITIALIZATION FOR REGISTER A3_COEFF_HDR0_TX2
#define A3_COEFF_HDR0_TX2_1			0XA6 ///< ADDRESS=166
#define A3_COEFF_HDR0_TX2_MSB_1			23
#define A3_COEFF_HDR0_TX2_LSB_1			16
#define A3_COEFF_HDR0_TX2			0XA7 ///< ADDRESS=167
#define A3_COEFF_HDR0_TX2_MSB			23
#define A3_COEFF_HDR0_TX2_LSB			16

//INITIALIZATION FOR REGISTER A3_COEFF_HDR1_TX2
#define A3_COEFF_HDR1_TX2_1			0XA8 ///< ADDRESS=168
#define A3_COEFF_HDR1_TX2_MSB_1			23
#define A3_COEFF_HDR1_TX2_LSB_1			16
#define A3_COEFF_HDR1_TX2			0XA9 ///< ADDRESS=169
#define A3_COEFF_HDR1_TX2_MSB			23
#define A3_COEFF_HDR1_TX2_LSB			16

//INITIALIZATION FOR REGISTER A4_COEFF_HDR1_TX0
#define A4_COEFF_HDR1_TX0_1			0XAA ///< ADDRESS=170
#define A4_COEFF_HDR1_TX0_MSB_1			23
#define A4_COEFF_HDR1_TX0_LSB_1			16
#define A4_COEFF_HDR1_TX0			0XAB ///< ADDRESS=171
#define A4_COEFF_HDR1_TX0_MSB			23
#define A4_COEFF_HDR1_TX0_LSB			16

//INITIALIZATION FOR REGISTER A4_COEFF_HDR0_TX1
#define A4_COEFF_HDR0_TX1_1			0XAC ///< ADDRESS=172
#define A4_COEFF_HDR0_TX1_MSB_1			23
#define A4_COEFF_HDR0_TX1_LSB_1			16
#define A4_COEFF_HDR0_TX1			0XAD ///< ADDRESS=173
#define A4_COEFF_HDR0_TX1_MSB			23
#define A4_COEFF_HDR0_TX1_LSB			16

//INITIALIZATION FOR REGISTER A4_COEFF_HDR1_TX1
#define A4_COEFF_HDR1_TX1_1			0XAE ///< ADDRESS=174
#define A4_COEFF_HDR1_TX1_MSB_1			23
#define A4_COEFF_HDR1_TX1_LSB_1			16
#define A4_COEFF_HDR1_TX1			0XAF ///< ADDRESS=175
#define A4_COEFF_HDR1_TX1_MSB			23
#define A4_COEFF_HDR1_TX1_LSB			16

//INITIALIZATION FOR REGISTER A4_COEFF_HDR0_TX2
#define A4_COEFF_HDR0_TX2_1			0XB0 ///< ADDRESS=176
#define A4_COEFF_HDR0_TX2_MSB_1			23
#define A4_COEFF_HDR0_TX2_LSB_1			16
#define A4_COEFF_HDR0_TX2			0XB1 ///< ADDRESS=177
#define A4_COEFF_HDR0_TX2_MSB			23
#define A4_COEFF_HDR0_TX2_LSB			16

//INITIALIZATION FOR REGISTER A4_COEFF_HDR1_TX2
#define A4_COEFF_HDR1_TX2			0XB2 ///< ADDRESS=178
#define A4_COEFF_HDR1_TX2_MSB			15
#define A4_COEFF_HDR1_TX2_LSB			0

//INITIALIZATION FOR REGISTER TILLUM
#define TILLUM			0X04 ///< ADDRESS=4
#define TILLUM_MSB			19
#define TILLUM_LSB			8

//INITIALIZATION FOR REGISTER TSENS_SLAVE0
#define TSENS_SLAVE0			0X02 ///< ADDRESS=2
#define TSENS_SLAVE0_MSB			6
#define TSENS_SLAVE0_LSB			0

//INITIALIZATION FOR REGISTER TSENS_SLAVE1
#define TSENS_SLAVE1			0X02 ///< ADDRESS=2
#define TSENS_SLAVE1_MSB			13
#define TSENS_SLAVE1_LSB			7

//INITIALIZATION FOR REGISTER TSENS_SLAVE2
#define TSENS_SLAVE2			0X02 ///< ADDRESS=2
#define TSENS_SLAVE2_MSB			20
#define TSENS_SLAVE2_LSB			14

//INITIALIZATION FOR REGISTER CONFIG_TILLUM_MSB
#define CONFIG_TILLUM_MSB			0X07 ///< ADDRESS=7
#define CONFIG_TILLUM_MSB_MSB			23
#define CONFIG_TILLUM_MSB_LSB			20

//INITIALIZATION FOR REGISTER EN_TILLUM_12B
#define EN_TILLUM_12B			0X0D ///< ADDRESS=13
#define EN_TILLUM_12B_MSB			23
#define EN_TILLUM_12B_LSB			23

//INITIALIZATION FOR REGISTER TILLUM_UNSIGNED
#define TILLUM_UNSIGNED			0X04 ///< ADDRESS=4
#define TILLUM_UNSIGNED_MSB			23
#define TILLUM_UNSIGNED_LSB			23

//INITIALIZATION FOR REGISTER TEMP_AVG_ILLUM
#define TEMP_AVG_ILLUM			0X02 ///< ADDRESS=2
#define TEMP_AVG_ILLUM_MSB			23
#define TEMP_AVG_ILLUM_LSB			22

//INITIALIZATION FOR REGISTER EN_TSENS_READ_FVD
#define EN_TSENS_READ_FVD			0X03 ///< ADDRESS=3
#define EN_TSENS_READ_FVD_MSB			18
#define EN_TSENS_READ_FVD_LSB			18

//INITIALIZATION FOR REGISTER EN_TILLUM_READ
#define EN_TILLUM_READ			0X02 ///< ADDRESS=2
#define EN_TILLUM_READ_MSB			21
#define EN_TILLUM_READ_LSB			21

//INITIALIZATION FOR REGISTER EEPROM_READ_TRIG
#define EEPROM_READ_TRIG			0X01 ///< ADDRESS=1
#define EEPROM_READ_TRIG_MSB			0
#define EEPROM_READ_TRIG_LSB			0

//INITIALIZATION FOR REGISTER SWAP_READ_DATA
#define SWAP_READ_DATA			0X01 ///< ADDRESS=1
#define SWAP_READ_DATA_MSB			1
#define SWAP_READ_DATA_LSB			1

//INITIALIZATION FOR REGISTER EEPROM_START_REG_ADDR
#define EEPROM_START_REG_ADDR			0X01 ///< ADDRESS=1
#define EEPROM_START_REG_ADDR_MSB			16
#define EEPROM_START_REG_ADDR_LSB			9

//INITIALIZATION FOR REGISTER FRAME_VD_TRIG
#define FRAME_VD_TRIG			0X01 ///< ADDRESS=1
#define FRAME_VD_TRIG_MSB			17
#define FRAME_VD_TRIG_LSB			17

//INITIALIZATION FOR REGISTER I2C_TRIG_REG
#define I2C_TRIG_REG			0X01 ///< ADDRESS=1
#define I2C_TRIG_REG_MSB			18
#define I2C_TRIG_REG_LSB			18

//INITIALIZATION FOR REGISTER I2C_EN
#define I2C_EN			0X01 ///< ADDRESS=1
#define I2C_EN_MSB			19
#define I2C_EN_LSB			19

//INITIALIZATION FOR REGISTER I2C_RW
#define I2C_RW			0X01 ///< ADDRESS=1
#define I2C_RW_MSB			21
#define I2C_RW_LSB			20

//INITIALIZATION FOR REGISTER I2C_READ_DATA
#define I2C_READ_DATA			0X03 ///< ADDRESS=3
#define I2C_READ_DATA_MSB			7
#define I2C_READ_DATA_LSB			0

//INITIALIZATION FOR REGISTER I2C_WRITE_DATA1
#define I2C_WRITE_DATA1			0X03 ///< ADDRESS=3
#define I2C_WRITE_DATA1_MSB			16
#define I2C_WRITE_DATA1_LSB			9

//INITIALIZATION FOR REGISTER I2C_NUM_TRAN
#define I2C_NUM_TRAN			0X03 ///< ADDRESS=3
#define I2C_NUM_TRAN_MSB			17
#define I2C_NUM_TRAN_LSB			17

//INITIALIZATION FOR REGISTER EN_EEPROM_READ
#define EN_EEPROM_READ			0X01 ///< ADDRESS=1
#define EN_EEPROM_READ_MSB			23
#define EN_EEPROM_READ_LSB			23

//INITIALIZATION FOR REGISTER INIT_LOAD_DONE
#define INIT_LOAD_DONE			0X03 ///< ADDRESS=3
#define INIT_LOAD_DONE_MSB			8
#define INIT_LOAD_DONE_LSB			8

//INITIALIZATION FOR REGISTER ADDR_SLAVE_EEPROM
#define ADDR_SLAVE_EEPROM			0X01 ///< ADDRESS=1
#define ADDR_SLAVE_EEPROM_MSB			8
#define ADDR_SLAVE_EEPROM_LSB			2

//INITIALIZATION FOR REGISTER I2C_NUM_BYTES_TRAN1
#define I2C_NUM_BYTES_TRAN1			0X07 ///< ADDRESS=7
#define I2C_NUM_BYTES_TRAN1_MSB			17
#define I2C_NUM_BYTES_TRAN1_LSB			16

//INITIALIZATION FOR REGISTER I2C_NUM_BYTES_TRAN2
#define I2C_NUM_BYTES_TRAN2			0X05 ///< ADDRESS=5
#define I2C_NUM_BYTES_TRAN2_MSB			23
#define I2C_NUM_BYTES_TRAN2_LSB			22

//INITIALIZATION FOR REGISTER I2C_WRITE_DATA2
#define I2C_WRITE_DATA2			0X07 ///< ADDRESS=7
#define I2C_WRITE_DATA2_MSB			7
#define I2C_WRITE_DATA2_LSB			0

//INITIALIZATION FOR REGISTER I2C_SEL_READ_BYTES
#define I2C_SEL_READ_BYTES			0X07 ///< ADDRESS=7
#define I2C_SEL_READ_BYTES_MSB			19
#define I2C_SEL_READ_BYTES_LSB			18

//INITIALIZATION FOR REGISTER I2C_CONT_RW
#define I2C_CONT_RW			0X00 ///< ADDRESS=0
#define I2C_CONT_RW_MSB			6
#define I2C_CONT_RW_LSB			6

//INITIALIZATION FOR REGISTER DIS_OVLDET
#define DIS_OVLDET			0X65 ///< ADDRESS=101
#define DIS_OVLDET_MSB			23
#define DIS_OVLDET_LSB			23

//INITIALIZATION FOR REGISTER PROG_OVLDET_REFP
#define PROG_OVLDET_REFP			0X64 ///< ADDRESS=100
#define PROG_OVLDET_REFP_MSB			20
#define PROG_OVLDET_REFP_LSB			18

//INITIALIZATION FOR REGISTER PROG_OVLDET_REFM
#define PROG_OVLDET_REFM			0X64 ///< ADDRESS=100
#define PROG_OVLDET_REFM_MSB			23
#define PROG_OVLDET_REFM_LSB			21

//INITIALIZATION FOR REGISTER IAMB_MAX_SEL
#define IAMB_MAX_SEL			0X72 ///< ADDRESS=114
#define IAMB_MAX_SEL_MSB			7
#define IAMB_MAX_SEL_LSB			4

//INITIALIZATION FOR REGISTER TM_VREFP_DIODE
#define TM_VREFP_DIODE			0X6D ///< ADDRESS=109
#define TM_VREFP_DIODE_MSB			2
#define TM_VREFP_DIODE_LSB			0

//INITIALIZATION FOR REGISTER TM_VREFM_DIODE
#define TM_VREFM_DIODE			0X6D ///< ADDRESS=109
#define TM_VREFM_DIODE_MSB			5
#define TM_VREFM_DIODE_LSB			3

//INITIALIZATION FOR REGISTER GPO1_MUX_SEL
#define GPO1_MUX_SEL			0X78 ///< ADDRESS=120
#define GPO1_MUX_SEL_MSB			8
#define GPO1_MUX_SEL_LSB			6

//INITIALIZATION FOR REGISTER GPIO1_OBUF_EN
#define GPIO1_OBUF_EN			0X78 ///< ADDRESS=120
#define GPIO1_OBUF_EN_MSB			12
#define GPIO1_OBUF_EN_LSB			12

//INITIALIZATION FOR REGISTER GPIO1_IBUF_EN
#define GPIO1_IBUF_EN			0X78 ///< ADDRESS=120
#define GPIO1_IBUF_EN_MSB			13
#define GPIO1_IBUF_EN_LSB			13

//INITIALIZATION FOR REGISTER GPO2_MUX_SEL
#define GPO2_MUX_SEL			0X78 ///< ADDRESS=120
#define GPO2_MUX_SEL_MSB			11
#define GPO2_MUX_SEL_LSB			9

//INITIALIZATION FOR REGISTER GPIO2_OBUF_EN
#define GPIO2_OBUF_EN			0X78 ///< ADDRESS=120
#define GPIO2_OBUF_EN_MSB			15
#define GPIO2_OBUF_EN_LSB			15

//INITIALIZATION FOR REGISTER GPIO2_IBUF_EN
#define GPIO2_IBUF_EN			0X78 ///< ADDRESS=120
#define GPIO2_IBUF_EN_MSB			16
#define GPIO2_IBUF_EN_LSB			16

//INITIALIZATION FOR REGISTER GPO3_MUX_SEL
#define GPO3_MUX_SEL			0X78 ///< ADDRESS=120
#define GPO3_MUX_SEL_MSB			2
#define GPO3_MUX_SEL_LSB			0

//INITIALIZATION FOR REGISTER SEL_GP3_ON_SDAM
#define SEL_GP3_ON_SDAM			0X78 ///< ADDRESS=120
#define SEL_GP3_ON_SDAM_MSB			22
#define SEL_GP3_ON_SDAM_LSB			22

//INITIALIZATION FOR REGISTER DEALIAS_EN
#define DEALIAS_EN			0X71 ///< ADDRESS=113
#define DEALIAS_EN_MSB			1
#define DEALIAS_EN_LSB			1

//INITIALIZATION FOR REGISTER DEALIAS_FREQ
#define DEALIAS_FREQ			0X71 ///< ADDRESS=113
#define DEALIAS_FREQ_MSB			2
#define DEALIAS_FREQ_LSB			2

//INITIALIZATION FOR REGISTER SHIFT_ILLUM_PHASE
#define SHIFT_ILLUM_PHASE			0X71 ///< ADDRESS=113
#define SHIFT_ILLUM_PHASE_MSB			6
#define SHIFT_ILLUM_PHASE_LSB			3

//INITIALIZATION FOR REGISTER SHUT_CLOCKS
#define SHUT_CLOCKS			0X71 ///< ADDRESS=113
#define SHUT_CLOCKS_MSB			8
#define SHUT_CLOCKS_LSB			8

//INITIALIZATION FOR REGISTER INVERT_TG_CLK
#define INVERT_TG_CLK			0X71 ///< ADDRESS=113
#define INVERT_TG_CLK_MSB			9
#define INVERT_TG_CLK_LSB			9

//INITIALIZATION FOR REGISTER INVERT_AFE_CLK
#define INVERT_AFE_CLK			0X71 ///< ADDRESS=113
#define INVERT_AFE_CLK_MSB			11
#define INVERT_AFE_CLK_LSB			11

//INITIALIZATION FOR REGISTER DIS_ILLUM_CLK_TX
#define DIS_ILLUM_CLK_TX			0X71 ///< ADDRESS=113
#define DIS_ILLUM_CLK_TX_MSB			12
#define DIS_ILLUM_CLK_TX_LSB			12

//INITIALIZATION FOR REGISTER EN_ILLUM_CLK_GPIO
#define EN_ILLUM_CLK_GPIO			0X71 ///< ADDRESS=113
#define EN_ILLUM_CLK_GPIO_MSB			16
#define EN_ILLUM_CLK_GPIO_LSB			16

//INITIALIZATION FOR REGISTER ILLUM_CLK_GPIO_MODE
#define ILLUM_CLK_GPIO_MODE			0X71 ///< ADDRESS=113
#define ILLUM_CLK_GPIO_MODE_MSB			15
#define ILLUM_CLK_GPIO_MODE_LSB			15

//INITIALIZATION FOR REGISTER UNMASK_ILLUMEN_INTXTALK
#define UNMASK_ILLUMEN_INTXTALK			0X71 ///< ADDRESS=113
#define UNMASK_ILLUMEN_INTXTALK_MSB			17
#define UNMASK_ILLUMEN_INTXTALK_LSB			17

//INITIALIZATION FOR REGISTER TEMP_OFFSET
#define TEMP_OFFSET			0X6E ///< ADDRESS=110
#define TEMP_OFFSET_MSB			16
#define TEMP_OFFSET_LSB			8

//INITIALIZATION FOR REGISTER EN_TEMP_CONV
#define EN_TEMP_CONV			0X6E ///< ADDRESS=110
#define EN_TEMP_CONV_MSB			19
#define EN_TEMP_CONV_LSB			19

//INITIALIZATION FOR REGISTER DIS_GLB_PD_REFSYS
#define DIS_GLB_PD_REFSYS			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_REFSYS_MSB			0
#define DIS_GLB_PD_REFSYS_LSB			0

//INITIALIZATION FOR REGISTER DIS_GLB_PD_TEMP_SENS
#define DIS_GLB_PD_TEMP_SENS			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_TEMP_SENS_MSB			1
#define DIS_GLB_PD_TEMP_SENS_LSB			1

//INITIALIZATION FOR REGISTER DIS_GLB_PD_ILLUM_DRV
#define DIS_GLB_PD_ILLUM_DRV			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_ILLUM_DRV_MSB			2
#define DIS_GLB_PD_ILLUM_DRV_LSB			2

//INITIALIZATION FOR REGISTER DIS_GLB_PD_AFE
#define DIS_GLB_PD_AFE			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_AFE_MSB			3
#define DIS_GLB_PD_AFE_LSB			3

//INITIALIZATION FOR REGISTER DIS_GLB_PD_AFE_DAC
#define DIS_GLB_PD_AFE_DAC			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_AFE_DAC_MSB			4
#define DIS_GLB_PD_AFE_DAC_LSB			4

//INITIALIZATION FOR REGISTER DIS_GLB_PD_AMB_DAC
#define DIS_GLB_PD_AMB_DAC			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_AMB_DAC_MSB			5
#define DIS_GLB_PD_AMB_DAC_LSB			5

//INITIALIZATION FOR REGISTER DIS_GLB_PD_AMB_ADC
#define DIS_GLB_PD_AMB_ADC			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_AMB_ADC_MSB			6
#define DIS_GLB_PD_AMB_ADC_LSB			6

//INITIALIZATION FOR REGISTER DIS_GLB_PD_TEST_CURR
#define DIS_GLB_PD_TEST_CURR			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_TEST_CURR_MSB			7
#define DIS_GLB_PD_TEST_CURR_LSB			7

//INITIALIZATION FOR REGISTER DIS_GLB_PD_OSC
#define DIS_GLB_PD_OSC			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_OSC_MSB			8
#define DIS_GLB_PD_OSC_LSB			8

//INITIALIZATION FOR REGISTER DIS_GLB_PD_I2CHOST
#define DIS_GLB_PD_I2CHOST			0X76 ///< ADDRESS=118
#define DIS_GLB_PD_I2CHOST_MSB			9
#define DIS_GLB_PD_I2CHOST_LSB			9

//INITIALIZATION FOR REGISTER PDN_GLOBAL
#define PDN_GLOBAL			0X76 ///< ADDRESS=118
#define PDN_GLOBAL_MSB			11
#define PDN_GLOBAL_LSB			11

//INITIALIZATION FOR REGISTER EN_DYN_PD_REFSYS
#define EN_DYN_PD_REFSYS			0X77 ///< ADDRESS=119
#define EN_DYN_PD_REFSYS_MSB			0
#define EN_DYN_PD_REFSYS_LSB			0

//INITIALIZATION FOR REGISTER EN_DYN_PD_TEMP_SENS
#define EN_DYN_PD_TEMP_SENS			0X77 ///< ADDRESS=119
#define EN_DYN_PD_TEMP_SENS_MSB			1
#define EN_DYN_PD_TEMP_SENS_LSB			1

//INITIALIZATION FOR REGISTER EN_DYN_PD_ILLUM_DRV
#define EN_DYN_PD_ILLUM_DRV			0X77 ///< ADDRESS=119
#define EN_DYN_PD_ILLUM_DRV_MSB			2
#define EN_DYN_PD_ILLUM_DRV_LSB			2

//INITIALIZATION FOR REGISTER EN_DYN_PD_AFE
#define EN_DYN_PD_AFE			0X77 ///< ADDRESS=119
#define EN_DYN_PD_AFE_MSB			3
#define EN_DYN_PD_AFE_LSB			3

//INITIALIZATION FOR REGISTER EN_DYN_PD_AFE_DAC
#define EN_DYN_PD_AFE_DAC			0X77 ///< ADDRESS=119
#define EN_DYN_PD_AFE_DAC_MSB			4
#define EN_DYN_PD_AFE_DAC_LSB			4

//INITIALIZATION FOR REGISTER EN_DYN_PD_AMB_DAC
#define EN_DYN_PD_AMB_DAC			0X77 ///< ADDRESS=119
#define EN_DYN_PD_AMB_DAC_MSB			5
#define EN_DYN_PD_AMB_DAC_LSB			5

//INITIALIZATION FOR REGISTER EN_DYN_PD_AMB_ADC
#define EN_DYN_PD_AMB_ADC			0X77 ///< ADDRESS=119
#define EN_DYN_PD_AMB_ADC_MSB			6
#define EN_DYN_PD_AMB_ADC_LSB			6

//INITIALIZATION FOR REGISTER EN_DYN_PD_TEST_CURR
#define EN_DYN_PD_TEST_CURR			0X77 ///< ADDRESS=119
#define EN_DYN_PD_TEST_CURR_MSB			7
#define EN_DYN_PD_TEST_CURR_LSB			7

//INITIALIZATION FOR REGISTER EN_DYN_PD_OSC
#define EN_DYN_PD_OSC			0X77 ///< ADDRESS=119
#define EN_DYN_PD_OSC_MSB			8
#define EN_DYN_PD_OSC_LSB			8

//INITIALIZATION FOR REGISTER EN_DYN_PD_I2CHOST_OSC
#define EN_DYN_PD_I2CHOST_OSC			0X77 ///< ADDRESS=119
#define EN_DYN_PD_I2CHOST_OSC_MSB			9
#define EN_DYN_PD_I2CHOST_OSC_LSB			9

//INITIALIZATION FOR REGISTER TX0_PIN_CONFIG
#define TX0_PIN_CONFIG			0X7A ///< ADDRESS=122
#define TX0_PIN_CONFIG_MSB			5
#define TX0_PIN_CONFIG_LSB			4

//INITIALIZATION FOR REGISTER TX1_PIN_CONFIG
#define TX1_PIN_CONFIG			0X7A ///< ADDRESS=122
#define TX1_PIN_CONFIG_MSB			1
#define TX1_PIN_CONFIG_LSB			0

//INITIALIZATION FOR REGISTER TX2_PIN_CONFIG
#define TX2_PIN_CONFIG			0X7A ///< ADDRESS=122
#define TX2_PIN_CONFIG_MSB			3
#define TX2_PIN_CONFIG_LSB			2

//INITIALIZATION FOR REGISTER EN_TX_CLKB
#define EN_TX_CLKB			0X79 ///< ADDRESS=121
#define EN_TX_CLKB_MSB			0
#define EN_TX_CLKB_LSB			0

//INITIALIZATION FOR REGISTER EN_TX_CLKZ
#define EN_TX_CLKZ			0X79 ///< ADDRESS=121
#define EN_TX_CLKZ_MSB			2
#define EN_TX_CLKZ_LSB			2

//INITIALIZATION FOR REGISTER SEL_ILLUM_TX0_ON_TX1
#define SEL_ILLUM_TX0_ON_TX1			0X79 ///< ADDRESS=121
#define SEL_ILLUM_TX0_ON_TX1_MSB			3
#define SEL_ILLUM_TX0_ON_TX1_LSB			3

//INITIALIZATION FOR REGISTER ILLUM_DC_CURR_DAC
#define ILLUM_DC_CURR_DAC			0X79 ///< ADDRESS=121
#define ILLUM_DC_CURR_DAC_MSB			11
#define ILLUM_DC_CURR_DAC_LSB			8

//INITIALIZATION FOR REGISTER PDN_ILLUM_DC_CURR
#define PDN_ILLUM_DC_CURR			0X79 ///< ADDRESS=121
#define PDN_ILLUM_DC_CURR_MSB			12
#define PDN_ILLUM_DC_CURR_LSB			12

//INITIALIZATION FOR REGISTER FEEDBACK_CONT_MODE
#define FEEDBACK_CONT_MODE			0X79 ///< ADDRESS=121
#define FEEDBACK_CONT_MODE_MSB			13
#define FEEDBACK_CONT_MODE_LSB			13

//INITIALIZATION FOR REGISTER PDN_ILLUM_DRV
#define PDN_ILLUM_DRV			0X79 ///< ADDRESS=121
#define PDN_ILLUM_DRV_MSB			19
#define PDN_ILLUM_DRV_LSB			19

//INITIALIZATION FOR REGISTER EN_TX_DC_CURR_ALL
#define EN_TX_DC_CURR_ALL			0X79 ///< ADDRESS=121
#define EN_TX_DC_CURR_ALL_MSB			4

#endif //OPT3101_REGISTER_MAP_H
