/*
 *  sd_evt_handler.h
 *
 *  Created on: 05-Apr-2018
 *
 *  Copyright (c) 2018, Appiko
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification,
 *  are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice,
 *  this list of conditions and the following disclaimer.
 *
 *  2. Redistributions in binary form must reproduce the above copyright notice,
 *  this list of conditions and the following disclaimer in the documentation
 *  and/or other materials provided with the distribution.
 *
 *  3. Neither the name of the copyright holder nor the names of its contributors
 *  may be used to endorse or promote products derived from this software without
 *  specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 *  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 *  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 *  OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 */


/**
 * @addtogroup group_sd_assist
 * @{
 *
 * @defgroup group_evt_sd_handler Softdevice event handler
 *
 * @brief Module responsible for making sure that all the events
 *  generated by the Softdevice's SoC and BLE sections are received
 *  and passed on to handlers provided by the application.
 *
 * @{
 */


#ifndef CODEBASE_SD_ASSIST_EVT_SD_HANDLER_H_
#define CODEBASE_SD_ASSIST_SD_EVT_HANDLER_H_

#include "ble.h"

/**
 * @brief Initializes the SWI2 interrupt routine and stores the
 *  handlers for the BLE and SoC events.
 * @param ble_evt_handler
 * @param soc_evt_handler
 */
void evt_sd_handler_init(void (* ble_evt_handler)(ble_evt_t * ble_evt),
                         void (* soc_evt_handler)(uint32_t soc_evt_id));

#endif /* CODEBASE_SD_ASSIST_EVT_SD_HANDLER_H_ */

/**
 * @}
 * @}
 */
